# Site settings
title: Kunal's Scratchpad
email: knsn1994@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a scratchpad. 
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: so4pmaker
github_username:  knsn1994

# Build settings
markdown: kramdown
